---
- hosts: default
  vars_files:
    - vars.yaml
  tasks:
    - name: create keyring config directory
      file: >
        state=directory
        dest={{ keyring_config_dir }}

    - name: copy keyring config file to workaround https://bugs.launchpad.net/bugs/1242992
      copy: >
        src=files/keyringrc.cfg
        dest={{ keyring_config_dir }}/keyringrc.cfg

    - name: install git
      apt: "name=git update_cache=yes"
      sudo: True

    - name:
      file: >
        state=directory
        path=/opt/stack/devstack
        mode=777
        recurse=yes
      sudo: True

    - name: checkout devstack
      git: "repo=git://{{ git_mirror }}/openstack-dev/devstack.git dest=/opt/stack/devstack version={{ devstack_branch }} accept_hostkey=yes"

    - name: local.conf
      template: src=templates/local.conf.j2 dest=/opt/stack/devstack/local.conf

    - name: source openrc in profile
      lineinfile: dest=~/.profile regexp=".*openrc" line='. /opt/stack/devstack/openrc'

    - name: enable eth2
      command: ip link set dev eth2 up
      sudo: True
      when: vagrant_provider == "virtualbox"
